spring:
  datasource:
    # default port for mysql 3306
    url: jdbc:mysql://localhost:${PORT_DB}/${NAME_DB}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update